### ISSUE TITLE
forks to JuliaClimate org?

### ISSUE THREAD

**Issue by gaelforget** [CUPofTEAproject/DAMMmodel.jl#8]
Hi @AlexisRenchon 

was wondering whether you purposedly forked this repo and www.cupoftea.earth to JuliaClimate. Maybe you meant to transfer the repos to JuliaClimate, or to fork to your own GitHub account instead?

**Comment by AlexisRenchon** [comment]
Hi @gaelforget , I did this on purpose but I understand how this is confusing. I'm still wondering where these 2 open source and community oriented repo should live. I know it shouldn't be my personal github account, but an organization. 
It sounds good to me for now to have them on cupofteaproject organization and forked to juliaclimate, but if it is an issue with you I can remove them. Let me know! Thanks

**Comment by gaelforget** [comment]
Thanks for the quick feedback. A few thoughts:

- if you mean to transfer a repo then there is a functionality for that in github (see [here](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository))
- having these two repos under the cupofteaproject organization for now makes good sense to me
- transferring them to JuliaClimate could also be a good idea at some point, I feel, but that's ultimately up to you
- for forks, which are temporary in nature, I dont see why you would not send them to your own account instead; or what the point of sending them to the JuliaClimate org is

On the last one, this is basically what I do for JuliaClimate repos : fork them to my own account to do the dev / trial & error stuff using branches there, and PR back to the JuliaClimate repo if / when I feel it's ready for merge. I feel that this is a good way to avoid cluttering the main repo with a bunch of dev branches & so on.

On the JuliaClimate org side I feel that we should clarify expectations, but in my view it's a place for the community to host and obtain original material from, not one to clutter with forks for doing one's dev and then PR'ing back to some other org. Wouldn't you agree?

**Comment by AlexisRenchon** [comment]
Thanks for the explanations @gaelforget ! I do agree. I am still a beginner at Git and GitHub and didn't know all the layers you explained. It makes sense. I will remove the forks. 
I do my PR locally but I'll keep in mind the option of forking to my personal github, I think when my projects are more mature it will make more sense. 
Also, maybe I'll move my repos to JuliaClimate in the future (for v1.0?) we will see. 
In the meantime, happy new year!

**Comment by gaelforget** [comment]
Cool. Welcome to GitHub and thanks for contributing OSS! In case that's useful, we did [this doc](https://github.com/PraCTES/MIT-PraCTES/blob/master/demos/Lecture03_Project_Infrastructure/Lecture03_project_infrastructure.md) aimed at new MIT students a couple years ago.  Also I find that the [github guides](https://docs.github.com/en) are a great resource and the stuff I suggested earlier is [explained here](https://mitgcm.readthedocs.io/en/latest/contributing/contributing.html#git-setup) incl on git <-> GitHub. 

Happy new year to you as well. Cheers,
Gael
